Feature: Add product scan
Bibletoon/Fridger pull request #16
Opened 2024-08-07 17:25 UTC by Bibletoon

Closes #3

2024-08-08 05:58 UTC, bibletwink requested changes

2024-08-08 05:58 UTC, bibletwink commented on internal/errors/errors.go
> +	ErrResponseRead    = errors.New("response read error")
Не используются

2024-08-08 05:58 UTC, bibletwink commented on internal/handlers/photo.go
> +	return fmt.Sprintf("Product %s successfully deleted", product.Name)
1. Переписать сообщения на Русский (чтобы названия продуктов не выбивались)
2. Кажется не стоит возвращать текст ошибки в сообщении, лучше делать лог + "Возникла ошибка"
3. Можно сделать отдельные сообщения для ошибки распознавания кода и поиска продукта

2024-08-08 05:58 UTC, bibletwink commented on internal/domain/models/product.go
> +	Cis            string
`Cis` вроде как не какое-то общепринятое наименование, кажется лучше придумать более понятное название

2024-08-08 05:58 UTC, bibletwink commented on internal/infrastructure/clients/dto/product_info.go
> +type ProductInfoDto struct {
Кажется приписка `Dto` лишняя

2024-08-08 05:58 UTC, bibletwink commented on internal/infrastructure/repositories/product.go
> +			Values(product.Name, product.Gtin, product.Cis, product.Category, product.ExpirationDate, product.IsActive, product.CreatedAt).
Опасно длинная строка, лучше поправить форматирование

2024-08-08 05:58 UTC, bibletwink commented on internal/infrastructure/repositories/product.go
> +		}
Надо поресёрчить какие Best Practice для методов Find/Get в Go. Возможно лучше сделать метод Get* возвращающий ошибку NotFound

2024-08-08 16:21 UTC, Bibletoon commented on internal/handlers/photo.go
> +	return fmt.Sprintf("Product %s successfully deleted", product.Name)
Done

2024-08-08 16:23 UTC, Bibletoon commented on internal/errors/errors.go
> +	ErrResponseRead    = errors.New("response read error")
Fixed

2024-08-08 16:27 UTC, Bibletoon commented on internal/infrastructure/repositories/product.go
> +			Values(product.Name, product.Gtin, product.Cis, product.Category, product.ExpirationDate, product.IsActive, product.CreatedAt).
Fixed

2024-08-08 16:27 UTC, Bibletoon commented on internal/infrastructure/repositories/product.go
> +		}
Сделал Get + NF

2024-08-08 16:27 UTC, Bibletoon commented on internal/infrastructure/clients/dto/product_info.go
> +type ProductInfoDto struct {
Fixed

2024-08-08 16:33 UTC, Bibletoon commented on internal/domain/models/product.go
> +	Cis            string
Fixed

2024-08-09 07:00 UTC, bibletwink approved these changes

2024-08-09 07:00 UTC, merged